     <footer>
        <p style="font-size: 80%;">&copy; Copyright <cfoutput>#Year(now())#</cfoutput> <a href="http://openbd.org/">OpenBD Open Source Java CFML Runtime Engine / Google App Engine</a> . All Rights Reserved . <a href="http://openbd.org/download/">Built &amp; Powered By OpenBD</a></p>
      </footer>
    </div> <!-- /container -->

		<script type="text/javascript" src="./js/js.cfm"/>
		<script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script>
		<script type="text/javascript">var pageTracker = _gat._getTracker("UA-153886-5");pageTracker._trackPageview();</script>

		<!-- Place this render call where appropriate -->
		<script type="text/javascript">
		  window.___gcfg = {lang: 'en-GB'};

		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/plusone.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
		<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>

  </body>
</html>