<cfset request.page.section = "basic">
<cfset request.page.title 	= "Basic CFML">
<cfset request.page.desc		= "CFML has a rich array of functions and rich variable types within the language to use">

<h1>Basic CFML</h1>

<ul class="breadcrumb">
	<li><a href="./?/basic_cfml">Basic CFML</a></li>
</ul>

<div class="row">

	<div class="span2">
		<h3>Overview</h3>
		<p>
		We've collected some primer documents for you to get to grips
		with the basics of CFML
		</p>

	</div>

	<div class="span14">

		<table>
		<tr>
			<td><a href="./?/language_tagsfunctions">Getting Started</a></td>
			<td>If you are completely new to CFML then this is page will get you started very quickly showing you the basics of the language and how it is constructed</td>
		</tr>
		<tr>
			<td><a href="./?/language_creation">Using Variables</a></td>
			<td>Discover how wonderfully rich and simple variables are to use in CFML</td>
		</tr>
		<tr>
			<td><a href="./?/language_scopes">Variable Scopes</a></td>
			<td>CFML has special language name spaces that let you get quickly at various types of data.</td>
		</tr>
		<tr>
			<td><a href="./?/language_operators">Data Operators</a></td>
			<td>While CFML is a typeless language, that does not mean you can't use standard operators on them.  This overviews them all.</td>
		</tr>
		<tr>
			<td><a href="./?/cfscript">Using CFSCRIPT</a></td>
			<td>CFSCRIPT is a powerful server side scripting language, not dissimilar to Javascript, that lets you code without using tags.</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td><a href="./?/cfc_introduction">CFML Objects</a></td>
			<td>CFML has a very power object model, that come in the form of CFC's.  Learn how to harness this power with little effort.</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td><a href="./?/app_application">CFML Application</a></td>
			<td>CFML can arrange your web apps in a special concept called an 'Application'.  These are powerful and can save you a lot of hassle.</td>
		</tr>
		<tr>
			<td><a href="./?/app_application_cfm">Application.cfm</a></td>
			<td>The Application.cfm concept is the template based version of the 'Application' that gets rendered before any other template.</td>
		</tr>
		<tr>
			<td><a href="./?/app_application_cfc">Application.cfc</a></td>
			<td>The Application.cfc is the more popular object orientated approach to handling applications, with callback methods on each type of event that happens.</td>
		</tr>
		<tr>
			<td><a href="./?/app_onrequestend_cfm">OnRequestEnd.cfm</a></td>
			<td>This is a special template that gets rendered on the end of each request.</td>
		</tr>
		<tr>
			<td><a href="./?/app_server_cfc">Server.cfc</a></td>
			<td>This template lets you hook into the startup of the server, initializing various settings that need to be done before you start servicing requests.</td>
		</tr>
		</table>



	</div>

</div>