<cfset request.page.title = "Support"><cfset request.page.section = "support">
<cfset request.page.desc	= "Getting Help with OpenBD">

<h1>Support</h1>

<p>
The OpenBD community is very active and helpful.   You can interact quickly and easily
using the official OpenBD Mailing list.
</p>

<p>
All are welcomed to join in the public discussion list.  This list is open to anyone wishing to discuss anything related to the Open BlueDragon open source J2EE project.
</p>

<p>
	<a href="http://groups.google.com/group/openbd" class="btn primary">Join our Google Discussion Group</a>
</p>
