<cfset request.page.title = "Support"><cfset request.page.section = "support">
<cfset request.page.desc	= "Getting Professional Support with OpenBD">

<h1>Support Professional</h1>

<p>
If you are looking for professional support, both incident based and policy based, then aw2.0 Ltd, the company
that sponsors the development of OpenBD can assist.
</p>


<p>
	<a href="http://www.aw20.co.uk" class="btn primary">Goto aw2.0 Ltd</a>
</p>
