<cfset request.page.title = "SVN"><cfset request.page.section = "support">
<cfset request.page.desc	= "Getting the source of OpenBD">

<h1>SVN</h1>

<p>
The OpenBD source code can be accessed anonymously from the SVN repository located here:
</p>

<ul><li> svn://svn.openbluedragon.org/openbd</li></ul>

<p>
The project requires a minimum of JDK 1.5 installed.  The project contains the necessary <a href="http://www.eclipse.org/" class="external text" title="http://www.eclipse.org/" rel="nofollow">Eclipse</a> project files and the <a href="http://ant.apache.org/" class="external text" title="http://ant.apache.org/" rel="nofollow">Ant</a> build scripts.
</p>

<p>
If you are not comfortable with using the svn command line version installed on most Linux systems, then you can use the popular
free <a href="http://www.syntevo.com/smartsvn/index.html" class="external text" title="http://www.syntevo.com/smartsvn/index.html" rel="nofollow">SmartSVN</a> client
that will run on any platform.  This is a graphical windows application that will make it easy for you to browse the project source.
</p>

<p>
Only code that has been validated by the core source control Tsar will be checked into the core branch.  If you want the latest cutting
edge build, then you will be able to download the nightly builds from the main web site.   Alternatively you can always use the latest stable
version.
</p>