#!/bin/sh

FIREFOX=`which firefox`
MOZILLA=`which mozilla`
EPIPHANY=`which epiphany`
KONQUEROR=`which konqueror`
NETSCAPE=`which netscape`
HOSTNAME=`hostname`
PORT=8088

if [ "$FIREFOX" != "" ]; then
    $FIREFOX http://$HOSTNAME:$PORT/fusionreactor &
elif [ "$MOZILLA" != "" ]; then
    $MOZILLA http://$HOSTNAME:$PORT/fusionreactor &
elif [ "$EPIPHANY" != "" ]; then
    $EPIPHANY http://$HOSTNAME:$PORT/fusionreactor &
elif [ "$KONQUEROR" != "" ]; then
    $KONQUEROR http://$HOSTNAME:$PORT/fusionreactor &
elif [ "$NETSCAPE" != "" ]; then
    $NETSCAPE http://$HOSTNAME:$PORT/fusionreactor &
else
    echo Could not find browser executable. Enter http://$HOSTNAME:$PORT/fusionreactor in a web browser to open FusionReactor Administrator.
fi
