<cfset request.page.title = "Acknowledgements">
<cfset request.page.desc	= "Thanking those that have contributed to the OpenBD Manual.">

<h1>Acknowledgements</h1>

<p>We would like to thank the following people for their contributions to this OpenBD manual.</p>

<p>
	<ul>
		<li><a href="http://alan.blog-city.com/">Alan Williamson</a></li>
		<li><a href="http://blog.mattwoodward.com/">Matthew Woodward</a></li>
		<li><a href="http://www.aw20.co.uk/">Andy Wu</a></li>
	</ul>
</p>

<p>We would also like to thank the many who have contributed and continue to contribute to our WIKI and Mailing Forums.</p>