
<div class="hero-unit">
	<h1>OpenBD Java CFML Engine</h1>

	<p>The power of one of the worlds easiest and most flexible web languages, without any of the cost, deployment problems or compromise.  Turbo charge your CFML development
	with OpenBD, the full enterprise open source GPL engine.</p>

	<p>
		This is the official manual for OpenBD.  Available both online and shipped with every download.
	</p>

	<p align="right"><a href="./?/basic_cfml" class="btn primary large">Get Started &raquo;</a></p>
</div>

<p>OpenBlueDragon (OpenBD) is the worlds first truly open source GPL Java CFML runtime engine.    CFML is a powerful script based language that takes away
all the heavy lifting of producing web based services and sites.   But CFML offers more than merely a set of tags and functions.</p>

<p>Often misunderstood, CFML can do far more to accelerate your enterprise requirements than almost any other language, running on top of the popular Java runtime, there
is no place OpenBD can't be deployed to.  From local laptop, to server, to Amazon, to Google App Engine.  We can go anywhere.</p>


<div class="row" style="margin-top: 40px;">

<div class="span5">
  <h2>Tags</h2>
  <p>OpenBD comes with a rich array of CFML tags, covering the core CFML language, as well as wonderful additions to the language that OpenBD has added to make your web development easier.</p>
  <p><a href="./?/tag/" class="btn" href="#">View Tags &raquo;</a></p>
</div>

<div class="span5">
  <h2>Functions</h2>
  <p>Functions are the life blood of the CFML language.  Whether you are writing tag based applications, or CFSCRIPT based applications, there is a function waiting for you to do pretty much anything.</p>
  <p><a href="./?/function/" class="btn" href="#">View Functions &raquo;</a></p>
</div>

<div class="span5">
  <h2>Bootstrap Application</h2>
  <p>Sometimes knowing where to start is the hardest thing, especially if you are new to the language.  Do not worry, we can help.  We have a bootstrap CFML site for you to get started and get up and running quickly.</p>
  <p><a class="btn" href="./?/bootstrap">Jump Start Me &raquo;</a></p>
</div>


</div>
