<cfset request.page.section = "adv">
<cfset request.page.title = "Advanced Concepts">
<cfset request.page.desc	= "Advanced CFML Concepts">

<h1>Advanced CFML Concepts</h1>

<ul class="breadcrumb">
	<li>Advanced Concepts</li>
</ul>

<div class="row">

	<div class="span2">
		<h3>Overview</h3>
		<p>
		Here we document some of the advance concepts
		</p>

	</div>

	<div class="span14">

		<table>
		<tr>
			<td><a href="./?/database_offrequest">Background Queries</a></td>
			<td>You can push some queries to the background instead of waiting for them to complete in a web request</td>
		</tr>
		<tr>
			<td><a href="./?/database_mongodb">MongoDB</a></td>
			<td>See how easy it is to work with the popular NoSQL MongoDB database with your CFML applications</td>
		</tr>
		<tr>
			<td><a href="./?/cookies">Cookies</a></td>
			<td>OpenBD has some advanced features for cookie handling</td>
		</tr>
		<tr>
			<td><a href="./?/cfscript_java">Embedded Java</a></td>
			<td>Did you know you can drop complete blocks of raw Java code/functions straight into your CFML pages.</td>
		</tr>
		<tr>
			<td><a href="./?/cfmlmanipulation">CFML Manipulation</a></td>
			<td>You can manipulate CFML pages from within CFML.  OpenBD provide helper functions/techniques for this.</td>
		</tr>
		<tr>
			<td><a href="./?/search">Search</a></td>
			<td>OpenBD comes with an advanced embedded search engine that can be used to index data, files and websites.</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td><a href="./?/webservices">Web Services</a></td>
			<td>An overview of how easy it is to utilise web services with OpenBD CFML.</td>
		</tr>
		<tr>
			<td><a href="./?/webservices_restlet">RESTlet</a></td>
			<td>You can easily create hosted RESTlet services for Javascript applications or other servers to consume.</td>
		</tr>
		<tr>
			<td><a href="./?/webservices_json">JSONP</a></td>
			<td>JSONP is a technique for Javascript applications to easily consume web services without breaking the browsers security.</td>
		</tr>
		<tr>
			<td><a href="./?/webservices_soap_producing">SOAP - Producing</a></td>
			<td>You can produce SOAP endpoints for your CFC's advertising their properties via WSDL.</td>
		</tr>
		<tr>
			<td><a href="./?/webservices_soap_consuming">SOAP - Consuming</a></td>
			<td>You can consume SOAP endpoints via their WSDL within your applications.</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td><a href="./?/amazon_s3">Amazon S3</a></td>
			<td>Discover how to work with Amazon's popular S3 cloud file storage.</td>
		</tr>
		<tr>
			<td><a href="./?/amazon_simpledb">Amazon SimpleDB</a></td>
			<td>See how you can work with Amazon's SimpleDB key/value cloud database.</td>
		</tr>
		<tr>
			<td><a href="./?/amazon_sqs">Amazon SQS</a></td>
			<td>Amazon Simple Queuing Server lets you send and consume messages.</td>
		</tr>

		</table>

	</div>

</div>