<h1>OpenBlueDragon Java CFML Runtime Engine</h1>

<p>OpenBlueDragon (OpenBD) is the worlds first truly open source GPL Java CFML runtime engine.    CFML is a powerful script based language that takes away
all the heavy lifting of producing web based services and sites.</p>

<p>But CFML offers more than merely a set of tags and functions.</p>

<p>Often misunderstood, CFML can do far more to accelerate your enterprise requirements than almost any other language, running on top of the popular Java runtime, there
is no place OpenBD can't be deployed to.</p>

<p>This manual has been put together to help all levels of skills to get to grips with OpenBD CFML, exploring topics from simple page creation right through to powering rich
web services.</p>

<p>You will be surprised just how much you can do, with very little code.</p>